language: c++

os:
    - linux
    #- windows

env:
    # Список переменных окружения, влияющих на матрицу сборки:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release        


install:
    # Скрипт настройки среды и установки зависимостей:
    - source ci/travis/install-$TRAVIS_OS_NAME.sh

compiler:
    - clang
 
packages:
    - cmake-data
    - cmake

script:
    # Сборочный скрипт
    - mkdir -p build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
    - cmake --build .
    #- ctest --output-on-failure
    
